[package]
name = "skyrim_savegame"
version = "0.1.0"
authors = ["Jupp56 <inf18241@lehre.dhbw-stuttgart.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4_flex = "0.7.5"
flate2 = "1.0.20"
anyhow = "1.0.40"